### ISSUE TITLE
robots: wasCrawlDisseminationWF:cdx-generator errors in production

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/was_robot_suite#13]
The `cdx-generator` robot is throwing a lot of error messages. These messages are similiar to the error messages in the old logs from Feb 2016.

The robot has successfully worked on a few objects, so we're assuming that it's working correctly and that the errors are related to either data or missing functionality. The `cdx-indexer` program is from the openwayback codebase and not ours, though we are using a fork of it here (openwayback-2.0.0.BETA.2.1): https://github.com/sul-dlss/openwayback/. 

Here is an example of an item that worked: 

https://argo.stanford.edu/catalog/druid:jj581ts2186

Here's an example item that failed:

https://argo.stanford.edu/catalog/druid:xf312dk5839

or search in Argo like so:

https://argo.stanford.edu/catalog?f%5Bwf_wps_ssim%5D%5B%5D=wasCrawlDisseminationWF%3Acdx-generator%3Aerror&page=1

Here is an example error message from the `log/cdx_indexer.log` file:

```
Jul 06, 2016 1:57:36 PM org.archive.io.ArchiveReader$ArchiveRecordIterator exceptionNext
WARNING: Failed to read http status where one was expected: 
```

and the error message for the overall step:

```
cdx-generator : Error in extracting CDX with command: jar/openwayback/bin/cdx-indexer /web-archiving-stacks/data/collections/kh149kf8484/xf/312/dk/5839/CDL-20090520014927-00038-oriole.ucop.edu-00082628.arc.gz /web-archiving-stacks/data/indices/cdx_working//druid:xf312dk5839/CDL-20090520014927-00038-oriole.ucop.edu-00082628.cdx 2>> log/cdx_indexer.log pid 8374 exit 1
```

but it appears that it is doing some work correctly and failing in mid-processing:

```
$ ls -1s /web-archiving-stacks/data/indices/cdx_working//druid:xf312dk5839
total 84200
3744 CDL-20090518134926-00000-oriole.ucop.edu-00082628.cdx
3796 CDL-20090518135111-00001-oriole.ucop.edu-00082628.cdx
2884 CDL-20090518150135-00002-oriole.ucop.edu-00082628.cdx
2796 CDL-20090518150610-00003-oriole.ucop.edu-00082628.cdx
3044 CDL-20090518163335-00004-oriole.ucop.edu-00082628.cdx
 500 CDL-20090518163802-00005-oriole.ucop.edu-00082628.cdx
3908 CDL-20090518165402-00006-oriole.ucop.edu-00082628.cdx
3696 CDL-20090518181047-00007-oriole.ucop.edu-00082628.cdx
3096 CDL-20090518190329-00008-oriole.ucop.edu-00082628.cdx
3116 CDL-20090518220611-00009-oriole.ucop.edu-00082628.cdx
2608 CDL-20090518235036-00010-oriole.ucop.edu-00082628.cdx
1704 CDL-20090519032548-00011-oriole.ucop.edu-00082628.cdx
 420 CDL-20090519034601-00012-oriole.ucop.edu-00082628.cdx
3160 CDL-20090519040624-00013-oriole.ucop.edu-00082628.cdx
3088 CDL-20090519044914-00014-oriole.ucop.edu-00082628.cdx
1952 CDL-20090519061516-00015-oriole.ucop.edu-00082628.cdx
1472 CDL-20090519065523-00016-oriole.ucop.edu-00082628.cdx
2640 CDL-20090519074529-00017-oriole.ucop.edu-00082628.cdx
2736 CDL-20090519075633-00018-oriole.ucop.edu-00082628.cdx
2408 CDL-20090519102951-00019-oriole.ucop.edu-00082628.cdx
2708 CDL-20090519113115-00020-oriole.ucop.edu-00082628.cdx
3072 CDL-20090519133034-00021-oriole.ucop.edu-00082628.cdx
2136 CDL-20090519135917-00022-oriole.ucop.edu-00082628.cdx
1888 CDL-20090519153741-00023-oriole.ucop.edu-00082628.cdx
1048 CDL-20090519154454-00024-oriole.ucop.edu-00082628.cdx
2252 CDL-20090519165950-00025-oriole.ucop.edu-00082628.cdx
2844 CDL-20090519173856-00026-oriole.ucop.edu-00082628.cdx
1520 CDL-20090519185058-00027-oriole.ucop.edu-00082628.cdx
2128 CDL-20090519194816-00028-oriole.ucop.edu-00082628.cdx
1772 CDL-20090519195942-00029-oriole.ucop.edu-00082628.cdx
2192 CDL-20090519214903-00030-oriole.ucop.edu-00082628.cdx
1964 CDL-20090519215622-00031-oriole.ucop.edu-00082628.cdx
1344 CDL-20090519233029-00032-oriole.ucop.edu-00082628.cdx
1200 CDL-20090519233315-00033-oriole.ucop.edu-00082628.cdx
1112 CDL-20090520003757-00034-oriole.ucop.edu-00082628.cdx
 964 CDL-20090520003855-00035-oriole.ucop.edu-00082628.cdx
 712 CDL-20090520011637-00036-oriole.ucop.edu-00082628.cdx
 576 CDL-20090520012220-00037-oriole.ucop.edu-00082628.cdx
   0 CDL-20090520014927-00038-oriole.ucop.edu-00082628.cdx
```

Here is the full exception:

```
Jul 06, 2016 2:14:58 PM org.archive.io.ArchiveReader$ArchiveRecordIterator exceptionNext
WARNING: Failed to read http status where one was expected: 
Exception in thread "main" java.lang.RuntimeException: Retried 10 times in a row
    at org.archive.io.ArchiveReader$ArchiveRecordIterator.exceptionNext(ArchiveReader.java:555)
    at org.archive.io.ArchiveReader$ArchiveRecordIterator.next(ArchiveReader.java:495)
    at org.archive.io.ArchiveReader$ArchiveRecordIterator.next(ArchiveReader.java:436)
    at org.archive.wayback.resourcestore.indexer.ArchiveReaderCloseableIterator.next(ArchiveReaderCloseableIterator.java:40)
    at org.archive.wayback.resourcestore.indexer.ArchiveReaderCloseableIterator.next(ArchiveReaderCloseableIterator.java:29)
    at org.archive.wayback.util.AdaptedIterator.hasNext(AdaptedIterator.java:56)
    at org.archive.wayback.util.AdaptedIterator.hasNext(AdaptedIterator.java:55)
    at org.archive.wayback.util.AdaptedIterator.hasNext(AdaptedIterator.java:55)
    at org.archive.wayback.resourcestore.indexer.IndexWorker.main(IndexWorker.java:216)
Caused by: java.io.IOException: Failed to read http status where one was expected: 
    at org.archive.io.arc.ARCRecord.readHttpHeader(ARCRecord.java:585)
    at org.archive.io.arc.ARCRecord.<init>(ARCRecord.java:208)
    at org.archive.io.arc.ARCReader.createArchiveRecord(ARCReader.java:149)
    at org.archive.io.arc.ARCReaderFactory$CompressedARCReader$1.innerNext(ARCReaderFactory.java:426)
    at org.archive.io.ArchiveReader$ArchiveRecordIterator.exceptionNext(ArchiveReader.java:537)
    ... 8 more
```

**Comment by drh-stanford** [comment]
Possibly related to https://github.com/sul-dlss/openwayback/issues/10?

**Comment by nullhandle** [comment]
All of the errors are related to legacy ARC files from two CDL WAS collections. Belated hash checking suggests that some accessioned data was corrupted for these collections, so that's likely the case. Otherwise, we should try reindexing with a more recent version of OpenWayback.

**Comment by ndushay** [comment]
There is a ticket to update openwayback
