### ISSUE TITLE
robots: audit of disk space used / leftover files no longer needed

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/was_robot_suite#21]
Step 1:  Do an audit of files used and written by all WF steps, and determine which ones remain under which circumstances.

if we can easily recreate a file, or if it is already in SDR / preservation / DOR / Solr ... can we delete it?  

Should this be part of the robot steps, or a separate cron job?

from @nullhandle "plan, but don't necessarily fix"

**Comment by drh-stanford** [comment]
The major space in production is from temporary files that were not cleaned up after an error:

```
[was@was-robots1-prod indices]$ ls -l cdx_working/pf139tj8228_*
-rw-r--r-- 1 was was     87225061 Dec  6 14:20 cdx_working/pf139tj8228_one_step_u_merged.cdx_3
-rw-r--r-- 1 was was 113142989698 Dec  6 17:33 cdx_working/pf139tj8228_sorted_index.cdx_1
-rw-r--r-- 1 was was 113142989698 Dec  8 22:56 cdx_working/pf139tj8228_sorted_index.cdx_2
-rw-r--r-- 1 was was 113142989698 Dec  9 02:08 cdx_working/pf139tj8228_sorted_index.cdx_3
[was@was-robots1-prod indices]$ pwd
/web-archiving-stacks/data/indices
```

The status of this object in DOR is in error:

```
dor_wasCrawlDisseminationWF_cdx-generator.log:ERROR [2015-11-10 10:19:52] (28114)  :: Error in extracting CDX with command: jar/openwayback/bin/cdx-indexer /web-archiving-stacks/data/collections/kh149kf8484/pf/139/tj/8228/CDL-20090720012817-00038-oriole.ucop.edu-00090279.arc.gz /web-archiving-stacks/data/indices/cdx_working//druid:pf139tj8228/CDL-20090720012817-00038-oriole.ucop.edu-00090279.cdx 2>> log/cdx_indexer.log
```

The dates do not match, so I suspect that these 300GB+ of files were created during this sprint. @ndushay were you using `pf139tj8228` as one of your test cases for the cdx generator step?

Note there are various errors in the logs for the cdx generator step that look like:

```
java.io.EOFException: Unexpected end of ZLIB input stream
        at org.archive.util.zip.OpenJDK7InflaterInputStream.fill(OpenJDK7InflaterInputStream.java:244)
        at org.archive.util.zip.OpenJDK7InflaterInputStream.read(OpenJDK7InflaterInputStream.java:162)
        at org.archive.util.zip.OpenJDK7GZIPInputStream.read(OpenJDK7GZIPInputStream.java:122)
        at org.archive.util.zip.GZIPMembersInputStream.read(GZIPMembersInputStream.java:113)
        at org.archive.io.ArchiveRecord.read(ArchiveRecord.java:204)
        at org.archive.io.arc.ARCRecord.read(ARCRecord.java:794)
        at org.archive.io.ArchiveRecord.skip(ArchiveRecord.java:262)
        at org.archive.io.ArchiveRecord.skip(ArchiveRecord.java:248)
        at org.archive.io.ArchiveRecord.close(ArchiveRecord.java:172)
        at org.archive.wayback.resourcestore.indexer.ARCRecordToSearchResultAdapter.adaptInner(ARCRecordToSearchResultAdapter.java:68)
        at org.archive.wayback.resourcestore.indexer.ARCRecordToSearchResultAdapter.adapt(ARCRecordToSearchResultAdapter.java:60)
        at org.archive.wayback.resourcestore.indexer.ARCRecordToSearchResultAdapter.adapt(ARCRecordToSearchResultAdapter.java:40)
        at org.archive.wayback.util.AdaptedIterator.hasNext(AdaptedIterator.java:57)
        at org.archive.wayback.util.AdaptedIterator.hasNext(AdaptedIterator.java:55)
        at org.archive.wayback.resourcestore.indexer.IndexWorker.main(IndexWorker.java:216)
Feb 23, 2016 11:14:57 PM org.archive.io.ArchiveReader$ArchiveRecordIterator hasNext
WARNING: Premature EOF cleaning up /web-archiving-stacks/data/collections/mm553tf6423/xg/370/vs/8494/CDL-20141201054821-00003-tanager.ucop.edu-00544379.arc.gz: {length=604911436, content-type=video/mp4, ip-address=23.216.10.137, creation-date=20141201060309, absolute-offset=9507427, subject-uri=http://www.whitehouse.gov/videos/2013/March/032813_GunSafety_HD.mp4, version=null}: Unexpected end of ZLIB input stream
```

**Comment by drh-stanford** [comment]
The `CDXMergeSortPublishService` does not handle error conditions when doing the sort/merge/publish. On error of the sorts, the `cdx_working/` folder does not get cleaned up. And on success, the individual CDX files are moved into `cdx_backup/` but are never cleaned up.

Since these files are strictly derivatives and we can re-generate them from the WARC files, I suggest that we have a cronjob that goes through these folders and removes any that are "old" (a month?). Otherwise, the space requirements double for the indices folders.

**Comment by ndushay** [comment]
actually, these are from my instrumenting and getting stats for the step, and can certainly be removed:

```
[was@was-robots1-prod indices]$ ls -l cdx_working/pf139tj8228_*
-rw-r--r-- 1 was was     87225061 Dec  6 14:20 cdx_working/pf139tj8228_one_step_u_merged.cdx_3
-rw-r--r-- 1 was was 113142989698 Dec  6 17:33 cdx_working/pf139tj8228_sorted_index.cdx_1
-rw-r--r-- 1 was was 113142989698 Dec  8 22:56 cdx_working/pf139tj8228_sorted_index.cdx_2
-rw-r--r-- 1 was was 113142989698 Dec  9 02:08 cdx_working/pf139tj8228_sorted_index.cdx_3
[was@was-robots1-prod indices]$ pwd
/web-archiving-stacks/data/indices
```

**Comment by ndushay** [comment]
I think the error info might be related to #13  -- maybe copy the info to their?    And make a separate ticket for doing the cron job to clean up the backup indexes?   We can then get a policy on those from @nullhandle

**Comment by ndushay** [comment]
from @drh-stanford 2016-12-12:

```
[lyberadmin@wayback-prod indices]$ du -hs *
113G	cdx
110G	cdx_backup
319G	cdx_working
35M	path
4.0K	path_working
```

**Comment by ndushay** [comment]
created #44 about cron job;  closing this in favor of #44, which is the action item to come out of this ...
