### ISSUE TITLE
A couple jobs taking a long time are blocking a restart of resque and more workers from starting

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/was_robot_suite#270]
**Describe the bug**

See https://stanfordlib.slack.com/archives/C09M7P91R/p1599685983186100

Currently there is one worker shown at https://robot-console-prod.stanford.edu/workers working on a massive job.

There should be 11: https://github.com/sul-dlss/was_robot_suite/blob/master/config/resque-pool.yml

There is a long running job (>1 TB) that could plausibly still be going.  But a deployment of dependency updates to prod didn't restart resque:

```
01:21 resque:pool:stop
      01 kill -s QUIT 5495
    ✔ 01 was@was-robots1-prod.stanford.edu 0.526s
      Waiting for pool manager to stop..
      Waiting for pool manager to stop..
      Waiting for pool manager to stop..
      Waiting for pool manager to stop..
      Waiting for pool manager to stop..
      Waiting for pool manager to stop..
      Waiting for pool manager to stop..
      Waiting for pool manager to stop..
      Waiting for pool manager to stop..
      Waiting for pool manager to stop..
      Waiting for pool manager to stop..
      Waiting for pool manager to stop..
      Waiting for pool manager to stop..
      Waiting for pool manager to stop..
      Waiting for pool manager to stop..
      Waiting for pool manager to stop..
      Waiting for pool manager to stop..
      Waiting for pool manager to stop..
      Waiting for pool manager to stop..
      Waiting for pool manager to stop..
      Waiting for pool manager to stop..
03:13 resque:pool:start
      01 bundle exec resque-pool --daemon --environment prod
      01 /opt/app/was/was_robot_suite/shared/bundle/ruby/2.6.0/gems/resque-pool-0.7.1/lib/resque/pool/cli.rb:104:in `manage_pidfile': Pidfile already exists at tmp/pids/resque-pool.pid and process is still running. (RuntimeError)
      01 	from /opt/app/was/was_robot_suite/shared/bundle/ruby/2.6.0/gems/resque-pool-0.7.1/lib/resque/pool/cli.rb:17:in `run'
      01 	from /opt/app/was/was_robot_suite/shared/bundle/ruby/2.6.0/gems/resque-pool-0.7.1/exe/resque-pool:7:in `<top (required)>'
      01 	from /opt/app/was/was_robot_suite/shared/bundle/ruby/2.6.0/bin/resque-pool:23:in `load'
      01 	from /opt/app/was/was_robot_suite/shared/bundle/ruby/2.6.0/bin/resque-pool:23:in `<main>'
      01 	from /opt/app/was/was_robot_suite/shared/bundle/ruby/2.6.0/bin/ruby_executable_hooks:24:in `eval'
      01 	from /opt/app/was/was_robot_suite/shared/bundle/ruby/2.6.0/bin/ruby_executable_hooks:24:in `<main>'
    ✔ 01 was@was-robots1-prod.stanford.edu 2.507s
```

We should look to see if those jobs need to be killed or are really running, and how to start other workers regardless.

**User Impact**

All new WAS jobs are stuck until we get more workers.

**Comment by mjgiarlo** [comment]
This specific situation has been resolved and we're hoping to remove the culprit component in the upcoming work cycle.

**Comment by lwrubel** [comment]
Closing since wasMetadataExtractor, we believe the culprit here, is not used in wasCrawlPreassembly anymore.
