### ISSUE TITLE
confirm the new robot VMs on stage are working properly

### ISSUE THREAD

**Issue by lmcglohon** [sul-dlss/was_robot_suite#41]
_From @lmcglohon on December 14, 2016 18:35_

The was-robots1-stage environment is ready for testing.

_Copied from original issue: sul-dlss/web-archiving#19_

**Comment by nullhandle** [comment]
I tried to access 3 crawl objects and encountered failure. Check the 332.pts-0 screen on was-registrar-stage for log output.

**Comment by drh-stanford** [comment]
Here is the error message for one of the failures:

```
Error in registering sul:SULWAS-SSH-FRENCH_ELECTIONS-20151013184207-2   French_elections/20151013184206 druid:mc744qd2082       druid:md569kj5536
 with 500 Internal Server Error: <?xml version="1.0" encoding="UTF-8"?>
<hash>
  <status type="integer">500</status>
  <error>Internal Server Error</error>
</hash>
/opt/app/was/was-registrar/shared/bundle/ruby/2.1.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!'
/opt/app/was/was-registrar/shared/bundle/ruby/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:495:in `process_result'
/opt/app/was/was-registrar/shared/bundle/ruby/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
/usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/net/http.rb:853:in `start'
/opt/app/was/was-registrar/shared/bundle/ruby/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
/opt/app/was/was-registrar/shared/bundle/ruby/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
/opt/app/was/was-registrar/shared/bundle/ruby/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
/opt/app/was/was-registrar/shared/bundle/ruby/2.1.0/gems/rest-client-1.8.0/lib/restclient/resource.rb:67:in `post'
/opt/app/was/was-registrar/releases/20160707190530/lib/was/registrar/register_object.rb:35:in `register_object_using_web_service'
/opt/app/was/was-registrar/releases/20160707190530/lib/was/registrar/register_object.rb:17:in `register'
/opt/app/was/was-registrar/releases/20160707190530/lib/was/registrar/register_crawl_object_from_file.rb:25:in `block in register'
/opt/app/was/was-registrar/releases/20160707190530/lib/was/registrar/register_crawl_object_from_file.rb:21:in `each'
/opt/app/was/was-registrar/releases/20160707190530/lib/was/registrar/register_crawl_object_from_file.rb:21:in `each_with_index'
/opt/app/was/was-registrar/releases/20160707190530/lib/was/registrar/register_crawl_object_from_file.rb:21:in `register'
/opt/app/was/was-registrar/releases/20160707190530/lib/tasks/registering_crawl.rake:13:in `block (2 levels) in <top (required)>'
/opt/app/was/was-registrar/shared/bundle/ruby/2.1.0/gems/rake-11.2.2/lib/rake/task.rb:248:in `call'
/opt/app/was/was-registrar/shared/bundle/ruby/2.1.0/gems/rake-11.2.2/lib/rake/task.rb:248:in `block in execute'
/opt/app/was/was-registrar/shared/bundle/ruby/2.1.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `each'
/opt/app/was/was-registrar/shared/bundle/ruby/2.1.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'
/opt/app/was/was-registrar/shared/bundle/ruby/2.1.0/gems/rake-11.2.2/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/opt/app/was/was-registrar/shared/bundle/ruby/2.1.0/gems/rake-11.2.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
/opt/app/was/was-registrar/shared/bundle/ruby/2.1.0/gems/rake-11.2.2/lib/rake/task.rb:173:in `invoke'
/opt/app/was/was-registrar/shared/bundle/ruby/2.1.0/gems/rake-11.2.2/lib/rake/application.rb:152:in `invoke_task'
/opt/app/was/was-registrar/shared/bundle/ruby/2.1.0/gems/rake-11.2.2/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/opt/app/was/was-registrar/shared/bundle/ruby/2.1.0/gems/rake-11.2.2/lib/rake/application.rb:108:in `each'
/opt/app/was/was-registrar/shared/bundle/ruby/2.1.0/gems/rake-11.2.2/lib/rake/application.rb:108:in `block in top_level'
/opt/app/was/was-registrar/shared/bundle/ruby/2.1.0/gems/rake-11.2.2/lib/rake/application.rb:117:in `run_with_threads'
/opt/app/was/was-registrar/shared/bundle/ruby/2.1.0/gems/rake-11.2.2/lib/rake/application.rb:102:in `top_level'
/opt/app/was/was-registrar/shared/bundle/ruby/2.1.0/gems/rake-11.2.2/lib/rake/application.rb:80:in `block in run'
/opt/app/was/was-registrar/shared/bundle/ruby/2.1.0/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
/opt/app/was/was-registrar/shared/bundle/ruby/2.1.0/gems/rake-11.2.2/lib/rake/application.rb:77:in `run'
/opt/app/was/was-registrar/shared/bundle/ruby/2.1.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/opt/app/was/was-registrar/shared/bundle/ruby/2.1.0/bin/rake:23:in `load'
/opt/app/was/was-registrar/shared/bundle/ruby/2.1.0/bin/rake:23:in `<main>'
```

**Comment by drh-stanford** [comment]
related to https://github.com/sul-dlss/was-registrar/issues/41

**Comment by ndushay** [comment]
Ok, I believe the current was-registrar code fixes the error above.  I don't know what box that log was on, or if the new VMs are pointing to was-registrar-stage ... but that is a working app and the code should be working, at least for seeds.  The stack trace above hits the code I had to fix for seeds.

**Comment by ndushay** [comment]
@nullhandle   can you please try
1.  seeds all the way thru the robots  for stage eco-system
2.  crawls all the way thru the robots for stage eco-system

I'm thinking seeds will work, and hoping that crawls will work.  I'm also hoping you did your trial with a crawl object before chris and I got the stage eco-system working for seeds ...

**Comment by drh-stanford** [comment]
the was-robots1 VMs are missing a few packages that we're installed on the old sul-robots3 VMs via old puppet. @tallenaz is working on migrating those in new puppet for the was-robots1 VMs. see https://github.com/sul-dlss/puppet/blob/085fd12b0ac0b10b2860bfac8563129d15120762/services/s_lyberservices/manifests/robots.pp#L4-L11

**Comment by tallenaz** [comment]
Related to sul-dlss/web-archiving#23

**Comment by tallenaz** [comment]
`was-robots1-*` have the missing packages. See https://github.com/sul-dlss/puppet/commit/d69b74a4b604302d6f50b74c2dfe4bc67bbe7c36

**Comment by ndushay** [comment]
I presume WASMetadataExtractor  jar got deployed properly?  Also think we might need hrwa_manager (see https://consul.stanford.edu/display/WARC/Downloading+WARCs+from+Archive-It)

**Comment by ndushay** [comment]
Seed:  missing phantomjs (used in thumbnail generation in seed preassembly workflow);  @tallenaz will fix puppet config and we'll try again.

```
INFO [2017-01-09 14:06:35] (48272)  :: Creating ThumbnailGenerator with parameters druid:bx957hh5027
which: no phantomjs in (/opt/app/was/was_robot_suite/shared/bundle/ruby/2.2.0/bin:/usr/local/rvm/gems/ruby-2.2.4/bin:/usr/local/rvm/gems/ruby-2.2.4@global/bin:/usr/local/rvm/rubies/ruby-2.2.4/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/rvm/bin:/opt/app/was/bin)```

**Comment by ndushay** [comment]
Are configs set up right?  `environment/test` seems like the wrong thing for  stage box 

```
Loading config from /opt/app/was/was_robot_suite/releases/20161214225121/config/environments/test
```

**Comment by ndushay** [comment]
@tallenaz  phantomjs good on `-stage`:  

```
INFO [2017-01-09 15:21:13] (128728)  :: druid:wy903fh8707 processing
 INFO [2017-01-09 15:21:13] (128728)  :: Creating ThumbnailGenerator with parameters druid:wy903fh8707
 INFO [2017-01-09 15:21:18] (128728)  :: Finished druid:wy903fh8707 in 4.8533s
```

please make it right on all 3 new robot VMs

**Comment by tallenaz** [comment]
`phantomjs` is on all 3 new robots VMs now.

**Comment by nullhandle** [comment]
Confirmed that the five test druids pasted into the Slack channel appear to have been accessioned fine.
