### ISSUE TITLE
cdxj-indexer step fails with large WARCs

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/was_robot_suite#545]
This druid failed at the cdxj-indexer step: https://argo.stanford.edu/view/druid:pg273nz1527. The WARC that it failed indexing is 4.9GB.

When re-running the step, `log/cdx_indexer.log` shows:
```
Traceback (most recent call last):
  File "/opt/app/was/.cache/pypoetry/virtualenvs/was-robot-suite-gi3TAXLu-py3.8/bin/cdxj-indexer", line 8, in <module>
    sys.exit(main())
  File "/opt/app/was/.cache/pypoetry/virtualenvs/was-robot-suite-gi3TAXLu-py3.8/lib/python3.8/site-packages/cdxj_indexer/main.py", line 518, 
in main
    write_cdx_index(cmd.output, cmd.inputs, vars(cmd))
  File "/opt/app/was/.cache/pypoetry/virtualenvs/was-robot-suite-gi3TAXLu-py3.8/lib/python3.8/site-packages/cdxj_indexer/main.py", line 533, 
in write_cdx_index
    indexer.process_all()
  File "/opt/app/was/.cache/pypoetry/virtualenvs/was-robot-suite-gi3TAXLu-py3.8/lib/python3.8/site-packages/cdxj_indexer/main.py", line 214, 
in process_all
    super().process_all()
  File "/opt/app/was/.cache/pypoetry/virtualenvs/was-robot-suite-gi3TAXLu-py3.8/lib/python3.8/site-packages/warcio/indexer.py", line 33, in p
rocess_all
    self.process_one(fh, out, filename)
  File "/opt/app/was/.cache/pypoetry/virtualenvs/was-robot-suite-gi3TAXLu-py3.8/lib/python3.8/site-packages/cdxj_indexer/main.py", line 248, 
in process_one
    for record in wrap_it:
  File "/opt/app/was/.cache/pypoetry/virtualenvs/was-robot-suite-gi3TAXLu-py3.8/lib/python3.8/site-packages/cdxj_indexer/bufferiter.py", line
 18, in buffering_record_iter
    buffer_record_content(record)
  File "/opt/app/was/.cache/pypoetry/virtualenvs/was-robot-suite-gi3TAXLu-py3.8/lib/python3.8/site-packages/cdxj_indexer/bufferiter.py", line
 95, in buffer_record_content
    shutil.copyfileobj(record.content_stream(), spool)
  File "/usr/lib/python3.8/shutil.py", line 208, in copyfileobj
    fdst_write(buf)
  File "/usr/lib/python3.8/tempfile.py", line 895, in write
    rv = file.write(s)
OSError: [Errno 28] No space left on device
```

**Comment by jcoyne** [comment]
Looks like it's out of space: 

```
OSError: [Errno 28] No space left on device
```

**Comment by edsu** [comment]
Is there any downside to using `/web-archiving-stacks/tmp/` as a temp space?

**Comment by lwrubel** [comment]
I see that `/web-archiving-stacks` has plenty of available space and while there is no `/web-archiving-stacks/tmp/` dir there at the moment there could be one created for this. I was following the pattern used for common-accessioning, which has `/imtmp` set up for image processing. Do you see an issue with using a separate tmpdir on was-robots? Maybe there is something I am missing about doing it this way?

**Comment by jcoyne** [comment]
Please don't use anything in `/web-archiving-stacks` for temp space.  I think that abuses the original purpose for that volume.  Make a new volume if necessary.

**Comment by edsu** [comment]
@jcoyne while I understand that `/web-archiving-stacks` is current being used to generate indexes.

**Comment by edsu** [comment]
@lwrubel I don't have any issue with using a separate volume, other than, there's now one more volume to manage, monitor, etc. I agree with you & @jcoyne that it makes sense to split things off. But that was probably a variation on the logic that led to `/web-archiving-stacks/data/indices` being a separate logical mount within `/web-archiving-stacks/` -- which I thought was a bit confusing.
