### ISSUE TITLE
Thumbnails should have a fixed height

### ISSUE THREAD

**Issue by peterchanws** [sul-dlss/was_robot_suite#561]
Thumbnail images should have a fixed height and not represent the full page. For example, this is not a useful thumbnail:

![default](https://user-images.githubusercontent.com/33829/187721731-704e19e0-c3ee-4a16-88d3-589d51f91103.jpg)

This thumbnail appears in Argo https://argo.stanford.edu/view/druid:rj850dd7965 and causes PURL to not even display the thumbnail: https://purl.stanford.edu/rj850dd7965.

PURL attempts to use this URL for the image https://stacks.stanford.edu/image/iiif/rj850dd7965%2Fthumbnail/full/200,/0/default.jpg but the image server throws an exception because of the requested scale:

```
$ curl https://stacks.stanford.edu/image/iiif/rj850dd7965%2Fthumbnail/full/200,/0/default.jpg
403 Forbidden

Requests for scales in excess of 100% are not allowed.


edu.illinois.library.cantaloupe.resource.ScaleRestrictedException: Requests for scales in excess of 100% are not allowed.
	at edu.illinois.library.cantaloupe.resource.PublicResource.validateScale(PublicResource.java:261)
	at edu.illinois.library.cantaloupe.resource.iiif.v2.ImageResource.access$300(ImageResource.java:31)
	at edu.illinois.library.cantaloupe.resource.iiif.v2.ImageResource$1CustomCallback.willProcessImage(ImageResource.java:112)
	at edu.illinois.library.cantaloupe.resource.ImageRequestHandler.handle(ImageRequestHandler.java:401)
	at edu.illinois.library.cantaloupe.resource.iiif.v2.ImageResource.doGET(ImageResource.java:128)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.handle(HandlerServlet.java:97)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.doGet(HandlerServlet.java:35)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by lwrubel** [comment]
This thumbnail was generated several years ago. Is the idea that purl should be able to render this? I'm not sure there's a problem with was_robot_suite doing this still. Puppeteer[ is setting a 1200 x 800 viewport](https://github.com/sul-dlss/was_robot_suite/blob/0dc68c9787d73e31edf2c592c9aca31707aee65d/scripts/screenshot.js#L27). 

I created a WACZ with a crawl of a Weibo profile and then registered a seed for it. It doesn't create a long image like that: https://argo-qa.stanford.edu/view/druid:pp500sc1756

**Comment by lwrubel** [comment]
Here's the PURL: https://sul-purl-stage.stanford.edu/pp500sc1756

**Comment by edsu** [comment]
Oh good, so this is no longer a problem! But we can't see the updated thumbnail because of https://github.com/sul-dlss/dor-services-app/issues/4146 

Closing.
