### ISSUE TITLE
cdxj-indexer failures: No space left on device

### ISSUE THREAD

**Issue by edsu** [sul-dlss/was_robot_suite#581]
We've been getting some HoneyBadger alerts about index failures:

https://app.honeybadger.io/projects/51141/faults/87026078

I took a look in the `cdx_indexer.log` file in production and saw some stack traces like this:

```
Traceback (most recent call last):
  File "/opt/app/was/.cache/pypoetry/virtualenvs/was-robot-suite-HzkhRPNn-py3.8/bin/cdxj-indexer", line 8, in <module>
    sys.exit(main())
  File "/opt/app/was/.cache/pypoetry/virtualenvs/was-robot-suite-HzkhRPNn-py3.8/lib/python3.8/site-packages/cdxj_indexer/main.py", line 518, in main
"log/cdx_indexer.log" 154L, 12348C                                                                22,1           6%
  File "/opt/app/was/.cache/pypoetry/virtualenvs/was-robot-suite-HzkhRPNn-py3.8/lib/python3.8/site-packages/cdxj_indexer/main.py", line 533, in write_cdx_index
    indexer.process_all()
  File "/opt/app/was/.cache/pypoetry/virtualenvs/was-robot-suite-HzkhRPNn-py3.8/lib/python3.8/site-packages/cdxj_indexer/main.py", line 214, in process_all
    super().process_all()
  File "/opt/app/was/.cache/pypoetry/virtualenvs/was-robot-suite-HzkhRPNn-py3.8/lib/python3.8/site-packages/warcio/indexer.py", line 33, in process_all
    self.process_one(fh, out, filename)
  File "/opt/app/was/.cache/pypoetry/virtualenvs/was-robot-suite-HzkhRPNn-py3.8/lib/python3.8/site-packages/cdxj_indexer/main.py", line 248, in process_one
    for record in wrap_it:
  File "/opt/app/was/.cache/pypoetry/virtualenvs/was-robot-suite-HzkhRPNn-py3.8/lib/python3.8/site-packages/cdxj_indexer/bufferiter.py", line 18, in buffering_record_iter
    buffer_record_content(record)
  File "/opt/app/was/.cache/pypoetry/virtualenvs/was-robot-suite-HzkhRPNn-py3.8/lib/python3.8/site-packages/cdxj_indexer/bufferiter.py", line 95, in buffer_record_content
    shutil.copyfileobj(record.content_stream(), spool)
  File "/usr/lib/python3.8/shutil.py", line 208, in copyfileobj
    fdst_write(buf)
  File "/usr/lib/python3.8/tempfile.py", line 895, in write
    rv = file.write(s)
OSError: [Errno 28] No space left on device
```

We may need to increase the size of the temp space that is used for sorting. Once resolved we should restart [these workflows](https://argo.stanford.edu/catalog?f%5Bwf_wps_ssim%5D%5B%5D=wasCrawlDisseminationWF%3Acdxj-generator%3Aerror) that are currently jammed up.

**Comment by edsu** [comment]
Watching the filesystem while the `cdxj-generator` workflow step is running I can see that despite the fact that `TMPDIR` is being set to `/warctmp` in the command, the `/tmp/` partition is being used instead, and that it quickly goes to 100% and then 1% after the process terminates and the temporary files are cleaned up.

I'm pretty sure we've had this working properly with `/warctmp` in the past--but perhaps not? There hasn't been a new version of cdxj-indexer since June 25, 2022 -- so I don't think it's a change in behavior of cdxj-indexer.

**Comment by edsu** [comment]
It looks to me like cdxj-indexer is using [NamedTemporaryFile](https://docs.python.org/3/library/tempfile.html?highlight=namedtemporaryfile#tempfile.NamedTemporaryFile) which (by my reading) should respect TMPDIR. So I'm confused why `/tmp` would be used.

**Comment by edsu** [comment]
I did some testing on stage and noticed that TMPDIR does seem to be getting used there. Basically I watched the filesystem with `watch df` while running this:

```
TMPDIR=/opt/app/was/was_robot_suite/current/tmp /opt/app/was/.local/bin/poetry run cdxj-indexer /web-archiving-stacks/data/collections/jt898xc8096/rj/881/kq/9882/ARCHIVEIT-5425-QUARTERLY-JOB1140531-SEED1050156-20200425114939029-00000-h3.warc.gz --output /web-archiving-stacks/data/indexes/cdxj_working/druid:jt898xc8096/ARCHIVEIT-5425-QUARTERLY-JOB1140531-SEED1050156-20200425114939029-00000-h3.warc.cdxj --dir-root /web-archiving-stacks/data/collections/ --post-append
```

I could see that the `/opt/app/` partition grew, and then shrank again. In the process I noticed that removing `--post-append` meant that it didn't seem to need to use TMPDIR at all. So the next thing is to take a look at cdxj-indexer again to see how it is doing sorting (the `NamedTemporaryFile` I mentioned above I think gets used when `--sort` is used).

**Comment by edsu** [comment]
I'm rerunning indexing for [bv757qp6679](https://argo.stanford.edu/view/druid:bv757qp6679) to test the new behavior with`/warctmp` owned by`was`. 🤞

**Comment by edsu** [comment]
That test for one worked, so I queued all of them to rerun the cdxj-indexing step.

**Comment by edsu** [comment]
All the workflows completed 🎉
